// Auto-generated by scripts/generate-themes.mjs — do not edit
import andromeeda from 'tm-themes/themes/andromeeda.json'
import auroraX from 'tm-themes/themes/aurora-x.json'
import ayuDark from 'tm-themes/themes/ayu-dark.json'
import ayuLight from 'tm-themes/themes/ayu-light.json'
import ayuMirage from 'tm-themes/themes/ayu-mirage.json'
import catppuccinFrappe from 'tm-themes/themes/catppuccin-frappe.json'
import catppuccinLatte from 'tm-themes/themes/catppuccin-latte.json'
import catppuccinMacchiato from 'tm-themes/themes/catppuccin-macchiato.json'
import catppuccinMocha from 'tm-themes/themes/catppuccin-mocha.json'
import darkPlus from 'tm-themes/themes/dark-plus.json'
import dracula from 'tm-themes/themes/dracula.json'
import draculaSoft from 'tm-themes/themes/dracula-soft.json'
import everforestDark from 'tm-themes/themes/everforest-dark.json'
import everforestLight from 'tm-themes/themes/everforest-light.json'
import githubDark from 'tm-themes/themes/github-dark.json'
import githubDarkDefault from 'tm-themes/themes/github-dark-default.json'
import githubDarkDimmed from 'tm-themes/themes/github-dark-dimmed.json'
import githubDarkHighContrast from 'tm-themes/themes/github-dark-high-contrast.json'
import githubLight from 'tm-themes/themes/github-light.json'
import githubLightDefault from 'tm-themes/themes/github-light-default.json'
import githubLightHighContrast from 'tm-themes/themes/github-light-high-contrast.json'
import gruvboxDarkHard from 'tm-themes/themes/gruvbox-dark-hard.json'
import gruvboxDarkMedium from 'tm-themes/themes/gruvbox-dark-medium.json'
import gruvboxDarkSoft from 'tm-themes/themes/gruvbox-dark-soft.json'
import gruvboxLightHard from 'tm-themes/themes/gruvbox-light-hard.json'
import gruvboxLightMedium from 'tm-themes/themes/gruvbox-light-medium.json'
import gruvboxLightSoft from 'tm-themes/themes/gruvbox-light-soft.json'
import horizon from 'tm-themes/themes/horizon.json'
import horizonBright from 'tm-themes/themes/horizon-bright.json'
import houston from 'tm-themes/themes/houston.json'
import kanagawaDragon from 'tm-themes/themes/kanagawa-dragon.json'
import kanagawaLotus from 'tm-themes/themes/kanagawa-lotus.json'
import kanagawaWave from 'tm-themes/themes/kanagawa-wave.json'
import laserwave from 'tm-themes/themes/laserwave.json'
import lightPlus from 'tm-themes/themes/light-plus.json'
import materialTheme from 'tm-themes/themes/material-theme.json'
import materialThemeDarker from 'tm-themes/themes/material-theme-darker.json'
import materialThemeLighter from 'tm-themes/themes/material-theme-lighter.json'
import materialThemeOcean from 'tm-themes/themes/material-theme-ocean.json'
import materialThemePalenight from 'tm-themes/themes/material-theme-palenight.json'
import minDark from 'tm-themes/themes/min-dark.json'
import minLight from 'tm-themes/themes/min-light.json'
import monokai from 'tm-themes/themes/monokai.json'
import nightOwl from 'tm-themes/themes/night-owl.json'
import nightOwlLight from 'tm-themes/themes/night-owl-light.json'
import nord from 'tm-themes/themes/nord.json'
import oneDarkPro from 'tm-themes/themes/one-dark-pro.json'
import oneLight from 'tm-themes/themes/one-light.json'
import plastic from 'tm-themes/themes/plastic.json'
import poimandres from 'tm-themes/themes/poimandres.json'
import red from 'tm-themes/themes/red.json'
import rosePine from 'tm-themes/themes/rose-pine.json'
import rosePineDawn from 'tm-themes/themes/rose-pine-dawn.json'
import rosePineMoon from 'tm-themes/themes/rose-pine-moon.json'
import slackDark from 'tm-themes/themes/slack-dark.json'
import slackOchin from 'tm-themes/themes/slack-ochin.json'
import snazzyLight from 'tm-themes/themes/snazzy-light.json'
import solarizedDark from 'tm-themes/themes/solarized-dark.json'
import solarizedLight from 'tm-themes/themes/solarized-light.json'
import synthwave84 from 'tm-themes/themes/synthwave-84.json'
import tokyoNight from 'tm-themes/themes/tokyo-night.json'
import vesper from 'tm-themes/themes/vesper.json'
import vitesseBlack from 'tm-themes/themes/vitesse-black.json'
import vitesseDark from 'tm-themes/themes/vitesse-dark.json'
import vitesseLight from 'tm-themes/themes/vitesse-light.json'

export const rawThemes = [
  { id: 'andromeeda', displayName: 'Andromeeda', dark: true, data: andromeeda },
  { id: 'aurora-x', displayName: 'Aurora X', dark: true, data: auroraX },
  { id: 'ayu-dark', displayName: 'Ayu Dark', dark: true, data: ayuDark },
  { id: 'ayu-light', displayName: 'Ayu Light', dark: false, data: ayuLight },
  { id: 'ayu-mirage', displayName: 'Ayu Mirage', dark: true, data: ayuMirage },
  {
    id: 'catppuccin-frappe',
    displayName: 'Catppuccin Frappé',
    dark: true,
    data: catppuccinFrappe,
  },
  {
    id: 'catppuccin-latte',
    displayName: 'Catppuccin Latte',
    dark: false,
    data: catppuccinLatte,
  },
  {
    id: 'catppuccin-macchiato',
    displayName: 'Catppuccin Macchiato',
    dark: true,
    data: catppuccinMacchiato,
  },
  {
    id: 'catppuccin-mocha',
    displayName: 'Catppuccin Mocha',
    dark: true,
    data: catppuccinMocha,
  },
  { id: 'dark-plus', displayName: 'Dark Plus', dark: true, data: darkPlus },
  { id: 'dracula', displayName: 'Dracula Theme', dark: true, data: dracula },
  {
    id: 'dracula-soft',
    displayName: 'Dracula Theme Soft',
    dark: true,
    data: draculaSoft,
  },
  {
    id: 'everforest-dark',
    displayName: 'Everforest Dark',
    dark: true,
    data: everforestDark,
  },
  {
    id: 'everforest-light',
    displayName: 'Everforest Light',
    dark: false,
    data: everforestLight,
  },
  {
    id: 'github-dark',
    displayName: 'GitHub Dark',
    dark: true,
    data: githubDark,
  },
  {
    id: 'github-dark-default',
    displayName: 'GitHub Dark Default',
    dark: true,
    data: githubDarkDefault,
  },
  {
    id: 'github-dark-dimmed',
    displayName: 'GitHub Dark Dimmed',
    dark: true,
    data: githubDarkDimmed,
  },
  {
    id: 'github-dark-high-contrast',
    displayName: 'GitHub Dark High Contrast',
    dark: true,
    data: githubDarkHighContrast,
  },
  {
    id: 'github-light',
    displayName: 'GitHub Light',
    dark: false,
    data: githubLight,
  },
  {
    id: 'github-light-default',
    displayName: 'GitHub Light Default',
    dark: false,
    data: githubLightDefault,
  },
  {
    id: 'github-light-high-contrast',
    displayName: 'GitHub Light High Contrast',
    dark: false,
    data: githubLightHighContrast,
  },
  {
    id: 'gruvbox-dark-hard',
    displayName: 'Gruvbox Dark Hard',
    dark: true,
    data: gruvboxDarkHard,
  },
  {
    id: 'gruvbox-dark-medium',
    displayName: 'Gruvbox Dark Medium',
    dark: true,
    data: gruvboxDarkMedium,
  },
  {
    id: 'gruvbox-dark-soft',
    displayName: 'Gruvbox Dark Soft',
    dark: true,
    data: gruvboxDarkSoft,
  },
  {
    id: 'gruvbox-light-hard',
    displayName: 'Gruvbox Light Hard',
    dark: false,
    data: gruvboxLightHard,
  },
  {
    id: 'gruvbox-light-medium',
    displayName: 'Gruvbox Light Medium',
    dark: false,
    data: gruvboxLightMedium,
  },
  {
    id: 'gruvbox-light-soft',
    displayName: 'Gruvbox Light Soft',
    dark: false,
    data: gruvboxLightSoft,
  },
  { id: 'horizon', displayName: 'Horizon', dark: true, data: horizon },
  {
    id: 'horizon-bright',
    displayName: 'Horizon Bright',
    dark: false,
    data: horizonBright,
  },
  { id: 'houston', displayName: 'Houston', dark: true, data: houston },
  {
    id: 'kanagawa-dragon',
    displayName: 'Kanagawa Dragon',
    dark: true,
    data: kanagawaDragon,
  },
  {
    id: 'kanagawa-lotus',
    displayName: 'Kanagawa Lotus',
    dark: false,
    data: kanagawaLotus,
  },
  {
    id: 'kanagawa-wave',
    displayName: 'Kanagawa Wave',
    dark: true,
    data: kanagawaWave,
  },
  { id: 'laserwave', displayName: 'LaserWave', dark: true, data: laserwave },
  { id: 'light-plus', displayName: 'Light Plus', dark: false, data: lightPlus },
  {
    id: 'material-theme',
    displayName: 'Material Theme',
    dark: true,
    data: materialTheme,
  },
  {
    id: 'material-theme-darker',
    displayName: 'Material Theme Darker',
    dark: true,
    data: materialThemeDarker,
  },
  {
    id: 'material-theme-lighter',
    displayName: 'Material Theme Lighter',
    dark: false,
    data: materialThemeLighter,
  },
  {
    id: 'material-theme-ocean',
    displayName: 'Material Theme Ocean',
    dark: true,
    data: materialThemeOcean,
  },
  {
    id: 'material-theme-palenight',
    displayName: 'Material Theme Palenight',
    dark: true,
    data: materialThemePalenight,
  },
  { id: 'min-dark', displayName: 'Min Dark', dark: true, data: minDark },
  { id: 'min-light', displayName: 'Min Light', dark: false, data: minLight },
  { id: 'monokai', displayName: 'Monokai', dark: true, data: monokai },
  { id: 'night-owl', displayName: 'Night Owl', dark: true, data: nightOwl },
  {
    id: 'night-owl-light',
    displayName: 'Night Owl Light',
    dark: false,
    data: nightOwlLight,
  },
  { id: 'nord', displayName: 'Nord', dark: true, data: nord },
  {
    id: 'one-dark-pro',
    displayName: 'One Dark Pro',
    dark: true,
    data: oneDarkPro,
  },
  { id: 'one-light', displayName: 'One Light', dark: false, data: oneLight },
  { id: 'plastic', displayName: 'Plastic', dark: true, data: plastic },
  { id: 'poimandres', displayName: 'Poimandres', dark: true, data: poimandres },
  { id: 'red', displayName: 'Red', dark: true, data: red },
  { id: 'rose-pine', displayName: 'Rosé Pine', dark: true, data: rosePine },
  {
    id: 'rose-pine-dawn',
    displayName: 'Rosé Pine Dawn',
    dark: false,
    data: rosePineDawn,
  },
  {
    id: 'rose-pine-moon',
    displayName: 'Rosé Pine Moon',
    dark: true,
    data: rosePineMoon,
  },
  { id: 'slack-dark', displayName: 'Slack Dark', dark: true, data: slackDark },
  {
    id: 'slack-ochin',
    displayName: 'Slack Ochin',
    dark: false,
    data: slackOchin,
  },
  {
    id: 'snazzy-light',
    displayName: 'Snazzy Light',
    dark: false,
    data: snazzyLight,
  },
  {
    id: 'solarized-dark',
    displayName: 'Solarized Dark',
    dark: true,
    data: solarizedDark,
  },
  {
    id: 'solarized-light',
    displayName: 'Solarized Light',
    dark: false,
    data: solarizedLight,
  },
  {
    id: 'synthwave-84',
    displayName: "Synthwave '84",
    dark: true,
    data: synthwave84,
  },
  {
    id: 'tokyo-night',
    displayName: 'Tokyo Night',
    dark: true,
    data: tokyoNight,
  },
  { id: 'vesper', displayName: 'Vesper', dark: true, data: vesper },
  {
    id: 'vitesse-black',
    displayName: 'Vitesse Black',
    dark: true,
    data: vitesseBlack,
  },
  {
    id: 'vitesse-dark',
    displayName: 'Vitesse Dark',
    dark: true,
    data: vitesseDark,
  },
  {
    id: 'vitesse-light',
    displayName: 'Vitesse Light',
    dark: false,
    data: vitesseLight,
  },
] as const
