/**
 * Generate a thin `raw.ts` that re-exports each TextMate theme JSON
 * from the `tm-themes` npm package. No color data is stored — all
 * color resolution happens at runtime via `resolve.ts`.
 *
 * Usage: node scripts/generate-themes.mjs
 */

import { writeFileSync } from 'fs'
import { join } from 'path'
import { themes } from 'tm-themes'

const OUT_FILE = join(import.meta.dirname, '../app/src/client/themes/raw.ts')

function toCamelCase(name) {
  return name.replace(/-([a-z0-9])/g, (_, c) => c.toUpperCase())
}

let ts = '// Auto-generated by scripts/generate-themes.mjs — do not edit\n'

for (const t of themes) {
  const varName = toCamelCase(t.name)
  ts += `import ${varName} from 'tm-themes/themes/${t.name}.json'\n`
}

ts += '\nexport const rawThemes = [\n'
for (const t of themes) {
  const varName = toCamelCase(t.name)
  ts += `  { id: '${t.name}', displayName: '${t.displayName.replace(/'/g, "\\'")}', dark: ${t.type === 'dark'}, data: ${varName} },\n`
}
ts += '] as const\n'

writeFileSync(OUT_FILE, ts, 'utf-8')
console.log(`✅ Generated ${themes.length} theme imports → ${OUT_FILE}`)
